-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 11:45:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AspEcomm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AspEcomm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AspEcomm` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `AspEcomm` ;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Users` (
  `user_ID` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `Zipcode` INT NULL DEFAULT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Sex` VARCHAR(20) NULL DEFAULT NULL,
  `Date_regd` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Date_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TransId` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `AspEcomm`.`Users` (`Email` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `phone_UNIQUE` ON `AspEcomm`.`Users` (`Phone` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Cars_for_Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Cars_for_Sale` (
  `Car_for_sale_ID` INT NOT NULL AUTO_INCREMENT,
  `manufacturer_sname` VARCHAR(50) NOT NULL,
  `model_code` INT NOT NULL,
  `category_code` INT NOT NULL,
  `asking_price` DOUBLE NOT NULL,
  `current_mileage` INT NOT NULL,
  `date_acquired` DATE NOT NULL,
  `date_registered` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `available` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Car_for_sale_ID`, `manufacturer_sname`, `model_code`, `category_code`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Car_Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Car_Models` (
  `model_code` INT NOT NULL,
  `manufacturer_code` VARCHAR(50) NOT NULL,
  `model_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`model_code`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `model_code_UNIQUE` ON `AspEcomm`.`Car_Models` (`model_code` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Car_Fatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Car_Fatures` (
  `car_feature_ID` INT NOT NULL,
  `car_feature_description` VARCHAR(140) NOT NULL,
  `car_feature_name` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `customers_ID_UNIQUE` ON `AspEcomm`.`Car_Fatures` (`car_feature_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Customer_Preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Customer_Preference` (
  `customer_preference_ID` INT NOT NULL,
  `car_feature_ID` INT NOT NULL,
  `customer_ID` INT NULL,
  `customer_Preference_details` VARCHAR(140) NULL,
  PRIMARY KEY (`customer_preference_ID`, `car_feature_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `customer_preference_ID_UNIQUE` ON `AspEcomm`.`Customer_Preference` (`customer_preference_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Car_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Car_Categories` (
  `car_category_code` INT NOT NULL AUTO_INCREMENT,
  `car_category_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`car_category_code`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCar_categories_UNIQUE` ON `AspEcomm`.`Car_Categories` (`car_category_code` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `car_category_name_UNIQUE` ON `AspEcomm`.`Car_Categories` (`car_category_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Car_Manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Car_Manufacturers` (
  `manufacturer_sname` VARCHAR(50) NOT NULL,
  `manufacturer_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`manufacturer_sname`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Addresses` (
  `address_ID` INT NOT NULL,
  `user_ID` INT NOT NULL,
  `address_line1` VARCHAR(100) NULL,
  `address_line2` VARCHAR(100) NULL,
  `address_line3` VARCHAR(100) NULL,
  `town_city` VARCHAR(100) NULL,
  `state` VARCHAR(100) NULL,
  `post_zip_code` INT NULL,
  PRIMARY KEY (`address_ID`, `user_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Payment_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Payment_Status` (
  `payment_status_code` INT NOT NULL,
  `payment_status_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`payment_status_code`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `payment_status_name_UNIQUE` ON `AspEcomm`.`Payment_Status` (`payment_status_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Customer_Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Customer_Payments` (
  `customer_payment_ID` INT NOT NULL,
  `car_sold_ID` INT NOT NULL,
  `payment_status_code` INT NOT NULL,
  `payment_due_date` DATE NOT NULL,
  `payment_amount` DOUBLE NULL,
  `payment_completed` DATETIME NULL,
  PRIMARY KEY (`customer_payment_ID`, `car_sold_ID`, `payment_status_code`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `AspEcomm`.`Car_Rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AspEcomm`.`Car_Rental` (
  `rental_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `car_sold_ID` INT NOT NULL,
  PRIMARY KEY (`rental_ID`, `car_sold_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
