<%@ Page Title="About Us" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="E_Commerce.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
   
        <h2><center><%: Title %></center></h2>
        <h3>Eiyo Autos</h3>
        <br />
        <p>
            LOREM IPSUM DOLOR SIT AMET CONSE CTETUR ADIPI SICING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE 
            MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCI TATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMMODO 
            CONSEQUAT. DUIS AUTE IRURE DOLOR IN REPREHE NDERIT IN VOLUPTATE VELIT ESSE CILLUM DOLORE.
        </p>
        <p>SIT AMET CONSE CTETUR ADIPISICING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT 
            ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT 
            ALIQUIP EX EA COMMODO CONSEQUAT. DUIS AUTE IRURE DOLOR IN REPREHENDERIT IN VOLUPTATE VELIT ESSE CILLUM DOLORE EU
            FUGIAT NULLA PARIATUR. EXCEPTEUR SINT OCCAECAT CUPIDATAT NON PROIDENT, SUNT IN CULPA QUI OFFICIA DESERUNT.
        </p>
</asp:Content>
